### ISSUE TITLE
Borrar fotos desde la carga de productos

### ISSUE THREAD

**Issue by facundoschiro** [sevenma7es/sevenma7es#4]
1) No me borra las fotos al clickear la x dentro de los productos en el panel administrador ✅
2) Si estoy logeado cuando entro a un producto me figura para que vuelva a ingresar ✅
3) el icono del modo oscuro en el panel de adminstrador esta al reves ✅

**Comment by mativiaggio** [comment]
Todos los puntos fueron resueltos.
